### ISSUE TITLE
Could not load type 'NP.Utilities.Point2D' from assembly 'NP.Utilities

### ISSUE THREAD

**Issue by henrrymoraes83** [npolyak/NP.Avalonia.UniDockService#2]
Hi

After upgrade from NP.Ava.UniDockService  1.0.4 to 1.0.5  it show this error message:

TypeLoadException: Could not load type 'NP.Utilities.Point2D' from assembly 'NP.Utilities, Version=1.0.28.0, Culture=neutral, PublicKeyToken=null'.

I didn't find the NP.Ava.UniDockService repositorie, so if you agree I will open this issue here on NP.Avalonia.UniDockService?

App.axaml

![image](https://github.com/user-attachments/assets/1e08615d-06be-447a-ac96-58c1dd1b3051)

Thank you so much!!

**Comment by npolyak** [comment]
That was due to mismatch in versions. Please, upgrade to UniDock 1.0.16 (which should also pull UniDockService 1.0.6) and that should resolve the problem, hopefully. 

Also note that in UniDock 1.0.16 I reference the latest stable Avalonia release - 11.1.3 - so you might need to update Avalonia references also.

Regards

**Comment by henrrymoraes83** [comment]
Please, Can you check if the UniDock 1.0.16  is available on nuget.org, for me the latest version is 1.0.15.

![image](https://github.com/user-attachments/assets/e682e31c-9ae2-4ee4-9f80-303438958aa6)


Thank you!!

**Comment by npolyak** [comment]
> Please, Can you check if the UniDock 1.0.16 is available on nuget.org, for me the latest version is 1.0.15.

Sorry, try it now. It should be there

**Comment by henrrymoraes83** [comment]
Excellent work!! Thanks

**Comment by henrrymoraes83** [comment]
UniDock 1.0.16 was uploaded on nuget. It fixed this issue.
